handle —host dev arg differently when given a boolean
nxtensions/nxtensions pull request #327
Opened 2023-03-07 22:46 UTC by supertommy

## What it does
This fixes an issue where setting { host: true } in the @nxtensions/astro:dev options config causes an error.

Instead of always passing the `host` arg as a string, this change checks the type of `host` and if it is a `boolean`:

- only adds --host if it is true
- does not add --host otherwise

For `string` types the behavior is as it was before.

2023-03-08 09:39 UTC, leosvelperez requested changes

2023-03-08 09:39 UTC, leosvelperez commented on packages/astro/src/executors/dev/executor.ts
> +    }
We also need to handle `false` correctly:
```suggestion
    if (typeof options.host === 'boolean') {
      args.push(options.host === true ? '--host' : '--no-host');
    } else {
      args.push('--host', options.host.toString());
    }
```

2023-03-09 20:16 UTC, supertommy reviewed
I couldn't find any documentation or code reference to `--no-host` in the astro source but it doesn't seem to hurt.

2023-03-09 21:53 UTC, leosvelperez approved these changes
Thanks for contributing! 🎉 

> I couldn't find any documentation or code reference to --no-host in the astro source but it doesn't seem to hurt.

You won't see `--no-host` directly in the source code. That is parsed to `host: false` by `yargs-parser`. You can see one usage of that `false` value here https://github.com/withastro/astro/blob/main/packages/astro/src/core/messages.ts#L182.

2023-03-09 21:53 UTC, merged