Update to nrwl nx 13.9.3
nxtensions/nxtensions pull request #45
Opened 2022-03-20 14:16 UTC by SebasG22

## What it does

Update Nx to the latest version 

## Related Issue(s)

Fixes #

2022-03-20 14:16 UTC, SebasG22 commented
Hey @leosvelperez, can you take a look?

2022-03-20 16:07 UTC, leosvelperez requested changes
Thanks for the contribution!

Just left a couple of small things to address and should be good to go 👍🏻

2022-03-20 16:07 UTC, leosvelperez commented on package.json
>      "@nrwl/cli": "13.8.2",
Please remove `@nrwl/cli`, it's no longer needed there.

2022-03-30 16:19 UTC, SebasG22 commented on package.json
> +    "nx": "13.9.3",
Done. Thanks for the suggestion

2022-05-04 17:28 UTC, leosvelperez commented
Yeah, I'll be updating the project to support Nx 14. I haven't merged this PR because there are issues with the deprecated `@astrojs/parser` in the current version that makes the plugin for the project graph not work correctly. I swapped it in a branch for the `@astrojs/compiler` but then there are some issues with it because it's distributed as ESM and the Nx CLI uses the https://www.npmjs.com/package/v8-compile-cache package which doesn't play well with ESM.

I'm trying to get that sorted out and when it's done, I'll close this PR in favor of another one adding support for Nx v14.

2022-05-04 17:47 UTC, leosvelperez commented
Actually, I went ahead and created the PR to update to the latest version of Nx (v14.1.1). I figured the issue with the project graph plugin is not depending on the Nx version upgrade. Better to have that update that solves a separate issue https://github.com/nxtensions/nxtensions/issues/46.

Closing this in favor of #47.

@SebasG22 thanks for the contribution and apologies for the delay!

2022-05-04 17:47 UTC, closed without merging